/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import Agents.Properties.cSkill;
import Agents.ProposerAgent;
import Agents.SolverAgent;
import Challenge.Challenge;
import Common.Logging.ILogManager;
import auresearch.FactoryHolder;
import javax.swing.JFrame;

/**
 *
 * @author d3vil401
 */
public class AgentInfoView extends javax.swing.JFrame {

    /**
     * Creates new form AgentInfoView
     */
    public AgentInfoView() {
        initComponents();
    }
    
    private Object _target = null;
    
    private void _addText(String _text)
    {
        this.jTextPane1.setText(this.jTextPane1.getText() + _text);
    }
    
    private void _loopProperties()
    {
        if (this._target instanceof SolverAgent)
        {
            SolverAgent _mask = (SolverAgent)this._target;
            this._addText("Skills: ");
            for (cSkill i: _mask.getSkills())
                if (i.getName().equals(FactoryHolder._configManager.getArrayValue("AGENT_SKILLS").get(FactoryHolder._configManager.getArrayValue("AGENT_SKILLS").size() - 1)))
                    this._addText(i.getName());
                else
                    this._addText(i.getName() + ", ");
            this._addText("\n");
            
            this._addText("Experience: " + _mask.getTotalExperience() + "\n");
            this._addText("Reward: " + _mask.getStats()._money + "\n");
            this._addText("Rejected Challenges: " + _mask.getStats()._rejected + "\n");
            this._addText("Solved Challenges: " + _mask.getStats()._successTrials + "\n");
            this._addText("Challenge Trials: " + _mask.getStats()._trials + "\n");
            this._addText("Challenge Fails: " + (_mask.getStats()._trials - _mask.getStats()._successTrials) + "\n");
            this._addText("\n");
            
            //this._addText("Last Challenges:\n");
            
        }
        // TODO: Rest of agents
    }
    
    public void setUpContent(Object _agent)
    {
        if (_agent instanceof SolverAgent)
        {
            this.jTextField1.setText(_agent.toString());
            this.jTextField2.setText("Solver Agent");
            this.jTextField3.setText(_agent.toString().split("#")[1]);
            this._target = _agent;
            this.jTextPane1.setText("");
            this._loopProperties();
        } else if (_agent instanceof ProposerAgent) {
            this.jTextField1.setText(_agent.toString());
            this.jTextField2.setText("Proposer Agent");
            this.jTextField3.setText(_agent.toString().split("#")[1]);
            this._target = _agent;
            this.jTextPane1.setText("");
            this._loopProperties();
        } else if (_agent instanceof Challenge) {
            this.jTextField1.setText(_agent.toString());
            this.jTextField2.setText("Challenge Entity");
            this.jTextField3.setText(_agent.toString().split("#")[1]);
            this._target = _agent;
            this.jTextPane1.setText("");
            this._loopProperties();
        } else {
            FactoryHolder._logManager.print(ILogManager._LOG_TYPE.TYPE_ERROR, "AgentInfoView request instance not recognized: " + _agent.toString());
        }
    }
    
    public AgentInfoView(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        
        //this.Graph_ActivityMonitor = FactoryHolder._graphicManager.renderGraph();
        //this.Graph_ActivityMonitor.add(FactoryHolder._graphicManager.renderGraph(), BorderLayout.CENTER);
        //this.Graph_ActivityMonitor.validate();
        //java.awt.image.BufferedImage image = FactoryHolder._graphicManager.renderGraph().getChart()
                //.createBufferedImage(this.Graph_ActivityMonitor.getWidth(), this.Graph_ActivityMonitor.getHeight());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setText("Agent name:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("Agent ID:");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Agent Type:");

        jTextPane1.setEditable(false);
        jTextPane1.setText("Skills: it, management, math, physics\nExperience: 3200\nReward: 8729 €\nRejected Challenges: 4\nResolved Challanges: 15\nChallenge Trials: 60\nChallenge Fails: 41\n\nLast Challenges:\n- Challenge#198273\n- Challenge#882739\n- Challenge#988138\n\n");
        jScrollPane1.setViewportView(jTextPane1);

        jTextField1.setEditable(false);
        jTextField1.setText("XAgent#X");
        jTextField1.setToolTipText("The internal name of the Agent/Challenge");

        jTextField2.setEditable(false);
        jTextField2.setText("?");

        jTextField3.setEditable(false);
        jTextField3.setText("27828");
        jTextField3.setToolTipText("");

        jButton1.setText("Close");

        jButton2.setText("Copy");

        jButton3.setText("Export");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(34, 34, 34))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 28, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
